
server:
  port: ${PORT:8080}
spring:
  profiles:
    active: ${PROFILE:development}
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: root
    platform: org.hibernate.dialect.H2Dialect
    continue-on-error: true
  sql:
    init: schema-locations=classpath:db.migration/V1_1__create_contact_table.sql
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      default_schema=phone_book_system:
      #ddl-auto: validate
    open-in-view: false #fixes the warning message... spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
  flyway:
    baselineOnMigrate: false
    baseline-version: 1  # sets baseline version
  data:
    web:
      pageable:
        one-indexed-parameters: true # set Pageable begin index to 1

